markdown: rdiscount
permalink: /:title/
url: helkyle.tk
name: helkyle.tk
author: helkyle
qq: 306295636
email: 306295636@qq.com
duoshuo: helkyle
beian: 浙ICP备12026616号
tongji: 950cb0948af29951cebc8bff62f400cd           # 百度统计ID
weibo: www.weibo.com/joueu
github: helkyle
highlighter: true
safe: true
paginate: 20
about: "这里是 helkyle 的个人博客，之前那个太花哨了~"
